@startuml
hide footbox
participant ":User" as User
participant ":ParserMain" as ParserMain
participant ":ParserFind" as ParserFind
participant ":BookFind" as BookFind
participant ":BookList" as BookList
participant ":BookMain" as BookMain
participant ":Ui" as Ui

User -> ParserMain: enter("find-title [title]")
ParserMain -> ParserFind: parseTitle(bookList, "[title]")
activate ParserFind

ParserFind -> BookFind: findBookTitle(bookList, "[title]")
activate BookFind

loop for each book in bookList
    BookFind -> BookList: getBooks()
    activate BookList
    BookList --> BookFind: books
    deactivate BookList

    BookFind -> BookMain: getTitle()
    activate BookMain
    BookMain --> BookFind: title
    deactivate BookMain

    alt if title contains "[title]"
        BookFind -> BookMain: add to bookTitles
    end
end

alt if bookTitles is not empty
    BookFind -> Ui: printBookFound(bookTitles)
else
    BookFind -> Ui: printNoBookFound()
end

deactivate BookFind
Ui -> User: display result
@enduml
